### ISSUE TITLE
Potential AWS Key Leakage

### ISSUE THREAD

**Issue by HarrisonLKatz** [thevaderdude/IrisML#4]
routes/authentication.js is still in git history, no clue if the key is revoked bc i'm not testing it out but the access key id ends with DSSA and the secret access key ends with 7Kq6. I don't use AWS much so no clue if that is important, was just testing out an app I downloaded on a few repos in my history and that came up in the audit.

**Comment by thevaderdude** [comment]
Yea @BobDunkeroo put his keys on the git and got charged $3000 a while ago but he deleted his keys. Thank you for the concern.
